spring:
  redis:
    database: 1
    host: localhost
    port: 6379
  session:
    store-type: redis
    timeout: 1800s
  mail:
    host: smtp.qq.com
    protocol: smtp
    port: 587
    default-encoding: utf-8
    username: 1150775734@qq.com
    password: svpizrswgjbvhfed
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
      ssl:
        enable: true

  datasource:
    url: jdbc:mysql://localhost:3306/zjwx?serverTimezone=UTC&useSSL=false&useUnicode=true&characterEncoding=utf-8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  configuration:
    map-underscore-to-camel-case: true

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  page-size-zero: false






